### PR TITLE
clean.conc.blq: feats for tmax reference

### PR DESCRIPTION
**Pull request by Gero1999**
Proposed in #340 

This is a potential solution for the opened topic in case you agree with any of the feat requests. There are two features associated with the commits in this PR:

- **Add before.tmax & after.tmax in conc.blq list argument**. In NCA is very typical to use tmax as a reference on how to deal with BLQ data. I changed PKNCA clean.conc.blq to include for the list definition "before.tmax" and "after.tmax" using the same logic as with `pk.calc.tfirst` but with `pk.calc.tmax`.

- **Default keep values in conc.blq list argument** . I feel that when a user does not define a specific scenario in the list argument (i.e, middle) they simply don't want to perform any action. For that reason, I modified PKNCA.options to put keep as the default value for list elements missing.

Feel free to give it a look, change or ignore/delete it!

### CODE REVIEW

**Comment by billdenney** [comment]
With a first read-through, the code looks good to me. Can you please:

1. Resolve the failing tests (row numbering can be resolved by setting data.frame row names to `NULL` within the function, I don't think that they are important).
2. Add tests for the new code. Please ensure that every line and every logical condition is tested.
3. Add the change to the News file

**Comment by Gero1999** [comment]
> With a first read-through, the code looks good to me. Can you please:
> 
> 1. Resolve the failing tests (row numbering can be resolved by setting data.frame row names to `NULL` within the function, I don't think that they are important).
> 2. Add tests for the new code. Please ensure that every line and every logical condition is tested.
> 3. Add the change to the News file
> 
> I may have additional comments after these. The above changes will make it easier to review everything and will be needed before merging.

Hello @billdenney I am not sure about what you meant with the row numbering and the data.frame names, but in principle I tried to solve all issues and implement new tests, so I hope it is fine!

**Comment by billdenney** [comment]
With my comment 1, when I was looking at the test errors, there appeared to be row number difference issues (which shouldn't matter). I will take a more careful look now and likely merge soon.

**Comment by billdenney** [comment]
Looks good! Thanks!

**Pull request merged**
